/*
 * This source file was generated by the Gradle 'init' task
 */
package generalizing.smt.solutions.fm4se;


import com.microsoft.z3.*;

import java.util.List;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

    
        SMTConnector connector = new SMTConnector();
        Context ctx = connector.getContext();

        IntExpr x = ctx.mkIntConst("x");
        IntExpr y = ctx.mkIntConst("y");

        BoolExpr formula = ctx.mkAnd(
            ctx.mkEq(x, ctx.mkInt(1)),
            ctx.mkGt(y, ctx.mkInt(0)),
            ctx.mkEq(ctx.mkInt(2), ctx.mkAdd(x,y))
        );

        ModelEnumerator enumerator = new ModelEnumerator(connector);
        List<Model> models = enumerator.enumerateSolutions(formula, 2);

        for (Model model : models)
        {
            System.out.println("Solution: " + model);
        }

        // Launch the interactive analyzer session.
        InteractiveAnalyzer analyzer = new InteractiveAnalyzer(connector);
        analyzer.runInteractiveSession(formula);

        // Clean up the context.
        connector.close();
        
    }
}


