/*
 * This source file was generated by the Gradle 'init' task
 */
package generalizing.smt.solutions.fm4se;

import com.microsoft.z3.*;

public class App {
    public static void testIntegerFormula(Context ctx) {
        // Create integer variables
        IntExpr x = ctx.mkIntConst("x");
        IntExpr y = ctx.mkIntConst("y");

        // Create a simple formula with integer constraints:
        // 1. x must be between 0 and 10: 0 <= x <= 10
        // 2. y must be greater than x: y > x
        // 3. y must be less than x + 5: y < x + 5
        BoolExpr formula = ctx.mkAnd(
            ctx.mkGe(x, ctx.mkInt(0)),     // x >= 0
            ctx.mkLe(x, ctx.mkInt(10)),    // x <= 10
            ctx.mkGt(y, x),                // y > x
            ctx.mkLt(y, ctx.mkAdd(x, ctx.mkInt(5)))  // y < x + 5
        );

        System.out.println("\n=== Testing Integer Formula ===");
        System.out.println("Test Formula with Integer Constraints:");
        System.out.println("1. 0 <= x <= 10");
        System.out.println("2. y > x");
        System.out.println("3. y < x + 5");
        System.out.println("\nThis formula has these properties:");
        System.out.println("- x is bounded between 0 and 10");
        System.out.println("- y must be greater than x but less than x + 5");
        System.out.println("- For each value of x, y has a specific valid interval");
        System.out.println("\nOriginal formula: " + formula);

        // Launch interactive analyzer for integer formula
        SMTConnector connector = new SMTConnector(ctx);
        InteractiveAnalyzer analyzer = new InteractiveAnalyzer(connector);
        analyzer.runInteractiveSession(formula);
    }

    public static void main(String[] args) {
        try (Context ctx = new Context()) {
            testIntegerFormula(ctx);
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace();
        }
    }
}


